name: Terraform Test Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Run Terraform Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init

      - name: Format Terraform files
        run: terraform fmt -check -recursive

      - name: Validate Terraform configuration
        run: terraform validate
